BYBIT_API_KEY = "3POalTNZRUD0AA38N3"
BYBIT_API_SECRET = "Wv0apOrJtZdzswyvrOLXiTMjhMCd0pPUHQiF"

TRADING_PAIRS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "AVAXUSDT", "LINKUSDT",
    "MATICUSDT", "DOGEUSDT", "LTCUSDT", "ATOMUSDT", "APTUSDT", "ARBUSDT",
    "OPUSDT", "INJUSDT", "NEARUSDT", "RNDRUSDT", "BLURUSDT", "SUIUSDT",
    "DYDXUSDT", "UNIUSDT", "PEPEUSDT", "TONUSDT", "1000SHIBUSDT", "GALAUSDT",
    "THETAUSDT", "ADAUSDT", "ETCUSDT"
]